In [8]:
import pandas

In [9]:
trees = pandas.read_csv('csvFiles/Sitka.csv')
trees

     Unnamed: 0  size  Time  tree    treat
0             1  4.51   152     1    ozone
1             2  4.98   174     1    ozone
2             3  5.41   201     1    ozone
3             4  5.90   227     1    ozone
4             5  6.15   258     1    ozone
5             6  4.24   152     2    ozone
6             7  4.20   174     2    ozone
7             8  4.68   201     2    ozone
8             9  4.92   227     2    ozone
9            10  4.96   258     2    ozone
10           11  3.98   152     3    ozone
11           12  4.36   174     3    ozone
12           13  4.79   201     3    ozone
13           14  4.99   227     3    ozone
14           15  5.03   258     3    ozone
15           16  4.36   152     4    ozone
16           17  4.77   174     4    ozone
17           18  5.10   201     4    ozone
18           19  5.30   227     4    ozone
19           20  5.36   258     4    ozone
20           21  4.34   152     5    ozone
21           22  4.95   174     5    ozone
22           23  5.42   201     5    ozone
23           24  5.97   227     5    ozone
24           25  6.28   258     5    ozone
25           26  4.59   152     6    ozone
26           27  5.08   174     6    ozone
27           28  5.36   201     6    ozone
28           29  5.76   227     6    ozone
29           30  6.00   258     6    ozone
..          ...   ...   ...   ...      ...
365         366  4.17   152    74  control
366         367  4.67   174    74  control
367         368  5.16   201    74  control
368         369  5.56   227    74  control
369         370  5.75   258    74  control
370         371  3.35   152    75  control
371         372  4.05   174    75  control
372         373  4.51   201    75  control
373         374  5.22   227    75  control
374         375  5.44   258    75  control
375         376  3.33   152    76  control
376         377  3.82   174    76  control
377         378  4.38   201    76  control
378         379  4.99   227    76  control
379         380  5.17   258    76  control
380         381  3.41   152    77  control
381         382  3.68   174    77  control
382         383  4.03   201    77  control
383         384  4.28   227    77  control
384         385  4.54   258    77  control
385         386  4.50   152    78  control
386         387  4.80   174    78  control
387         388  5.28   201    78  control
388         389  5.83   227    78  control
389         390  6.16   258    78  control
390         391  2.99   152    79  control
391         392  3.61   174    79  control
392         393  4.48   201    79  control
393         394  4.91   227    79  control
394         395  5.06   258    79  control

[395 rows x 5 columns]

In [20]:
type(trees)
trees.head()

   Unnamed: 0  size  Time  tree  treat
0           1  4.51   152     1  ozone
1           2  4.98   174     1  ozone
2           3  5.41   201     1  ozone
3           4  5.90   227     1  ozone
4           5  6.15   258     1  ozone

In [11]:
trees.tail()

     Unnamed: 0  size  Time  tree    treat
390         391  2.99   152    79  control
391         392  3.61   174    79  control
392         393  4.48   201    79  control
393         394  4.91   227    79  control
394         395  5.06   258    79  control

In [12]:
th = trees.head()
th

   Unnamed: 0  size  Time  tree  treat
0           1  4.51   152     1  ozone
1           2  4.98   174     1  ozone
2           3  5.41   201     1  ozone
3           4  5.90   227     1  ozone
4           5  6.15   258     1  ozone

In [13]:
th['Time']

0    152
1    174
2    201
3    227
4    258
Name: Time, dtype: int64

In [21]:
del trees['Unnamed: 0']

In [22]:
trees

     size  Time  tree    treat
0    4.51   152     1    ozone
1    4.98   174     1    ozone
2    5.41   201     1    ozone
3    5.90   227     1    ozone
4    6.15   258     1    ozone
5    4.24   152     2    ozone
6    4.20   174     2    ozone
7    4.68   201     2    ozone
8    4.92   227     2    ozone
9    4.96   258     2    ozone
10   3.98   152     3    ozone
11   4.36   174     3    ozone
12   4.79   201     3    ozone
13   4.99   227     3    ozone
14   5.03   258     3    ozone
15   4.36   152     4    ozone
16   4.77   174     4    ozone
17   5.10   201     4    ozone
18   5.30   227     4    ozone
19   5.36   258     4    ozone
20   4.34   152     5    ozone
21   4.95   174     5    ozone
22   5.42   201     5    ozone
23   5.97   227     5    ozone
24   6.28   258     5    ozone
25   4.59   152     6    ozone
26   5.08   174     6    ozone
27   5.36   201     6    ozone
28   5.76   227     6    ozone
29   6.00   258     6    ozone
..    ...   ...   ...      ...
365  4.17   152    74  control
366  4.67   174    74  control
367  5.16   201    74  control
368  5.56   227    74  control
369  5.75   258    74  control
370  3.35   152    75  control
371  4.05   174    75  control
372  4.51   201    75  control
373  5.22   227    75  control
374  5.44   258    75  control
375  3.33   152    76  control
376  3.82   174    76  control
377  4.38   201    76  control
378  4.99   227    76  control
379  5.17   258    76  control
380  3.41   152    77  control
381  3.68   174    77  control
382  4.03   201    77  control
383  4.28   227    77  control
384  4.54   258    77  control
385  4.50   152    78  control
386  4.80   174    78  control
387  5.28   201    78  control
388  5.83   227    78  control
389  6.16   258    78  control
390  2.99   152    79  control
391  3.61   174    79  control
392  4.48   201    79  control
393  4.91   227    79  control
394  5.06   258    79  control

[395 rows x 4 columns]

In [24]:
trees.columns = ['size', 'time', 'tree', 'treat']
trees

     size  time  tree    treat
0    4.51   152     1    ozone
1    4.98   174     1    ozone
2    5.41   201     1    ozone
3    5.90   227     1    ozone
4    6.15   258     1    ozone
5    4.24   152     2    ozone
6    4.20   174     2    ozone
7    4.68   201     2    ozone
8    4.92   227     2    ozone
9    4.96   258     2    ozone
10   3.98   152     3    ozone
11   4.36   174     3    ozone
12   4.79   201     3    ozone
13   4.99   227     3    ozone
14   5.03   258     3    ozone
15   4.36   152     4    ozone
16   4.77   174     4    ozone
17   5.10   201     4    ozone
18   5.30   227     4    ozone
19   5.36   258     4    ozone
20   4.34   152     5    ozone
21   4.95   174     5    ozone
22   5.42   201     5    ozone
23   5.97   227     5    ozone
24   6.28   258     5    ozone
25   4.59   152     6    ozone
26   5.08   174     6    ozone
27   5.36   201     6    ozone
28   5.76   227     6    ozone
29   6.00   258     6    ozone
..    ...   ...   ...      ...
365  4.17   152    74  control
366  4.67   174    74  control
367  5.16   201    74  control
368  5.56   227    74  control
369  5.75   258    74  control
370  3.35   152    75  control
371  4.05   174    75  control
372  4.51   201    75  control
373  5.22   227    75  control
374  5.44   258    75  control
375  3.33   152    76  control
376  3.82   174    76  control
377  4.38   201    76  control
378  4.99   227    76  control
379  5.17   258    76  control
380  3.41   152    77  control
381  3.68   174    77  control
382  4.03   201    77  control
383  4.28   227    77  control
384  4.54   258    77  control
385  4.50   152    78  control
386  4.80   174    78  control
387  5.28   201    78  control
388  5.83   227    78  control
389  6.16   258    78  control
390  2.99   152    79  control
391  3.61   174    79  control
392  4.48   201    79  control
393  4.91   227    79  control
394  5.06   258    79  control

[395 rows x 4 columns]

In [25]:
th = trees.head()

In [26]:
th.mean()

size      5.39
time    202.40
tree      1.00
dtype: float64

In [27]:
th['time'].mean()

202.4

In [34]:
th.describe()

           size        time  tree
count  5.000000    5.000000     5
mean   5.390000  202.400000     1
std    0.667196   41.967845     0
min    4.510000  152.000000     1
25%    4.980000  174.000000     1
50%    5.410000  201.000000     1
75%    5.900000  227.000000     1
max    6.150000  258.000000     1

In [39]:
trees.loc[trees['treat'] == 'ozone']

     size  time  tree  treat
0    4.51   152     1  ozone
1    4.98   174     1  ozone
2    5.41   201     1  ozone
3    5.90   227     1  ozone
4    6.15   258     1  ozone
5    4.24   152     2  ozone
6    4.20   174     2  ozone
7    4.68   201     2  ozone
8    4.92   227     2  ozone
9    4.96   258     2  ozone
10   3.98   152     3  ozone
11   4.36   174     3  ozone
12   4.79   201     3  ozone
13   4.99   227     3  ozone
14   5.03   258     3  ozone
15   4.36   152     4  ozone
16   4.77   174     4  ozone
17   5.10   201     4  ozone
18   5.30   227     4  ozone
19   5.36   258     4  ozone
20   4.34   152     5  ozone
21   4.95   174     5  ozone
22   5.42   201     5  ozone
23   5.97   227     5  ozone
24   6.28   258     5  ozone
25   4.59   152     6  ozone
26   5.08   174     6  ozone
27   5.36   201     6  ozone
28   5.76   227     6  ozone
29   6.00   258     6  ozone
..    ...   ...   ...    ...
240  3.31   152    49  ozone
241  3.45   174    49  ozone
242  4.16   201    49  ozone
243  4.48   227    49  ozone
244  4.54   258    49  ozone
245  3.03   152    50  ozone
246  3.55   174    50  ozone
247  3.97   201    50  ozone
248  4.40   227    50  ozone
249  4.58   258    50  ozone
250  3.27   152    51  ozone
251  3.83   174    51  ozone
252  4.44   201    51  ozone
253  4.80   227    51  ozone
254  4.89   258    51  ozone
255  3.56   152    52  ozone
256  4.18   174    52  ozone
257  4.70   201    52  ozone
258  5.27   227    52  ozone
259  5.28   258    52  ozone
260  3.39   152    53  ozone
261  3.73   174    53  ozone
262  3.92   201    53  ozone
263  4.11   227    53  ozone
264  4.15   258    53  ozone
265  3.72   152    54  ozone
266  4.16   174    54  ozone
267  4.55   201    54  ozone
268  5.03   227    54  ozone
269  5.02   258    54  ozone

[270 rows x 4 columns]

In [40]:
trees.loc[trees['tree'] == 1]

   size  time  tree  treat
0  4.51   152     1  ozone
1  4.98   174     1  ozone
2  5.41   201     1  ozone
3  5.90   227     1  ozone
4  6.15   258     1  ozone

In [43]:
trees.loc[trees['tree'] == 1]['size'].mean()

5.390000000000001

In [45]:
trees.loc[trees['time'] == 152]['size'].mean()

4.093291139240507

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
t1 = trees.loc[trees['tree'] == 1]
plt.plot(t1['time'],t1['size'])

In [ ]:
plt.xlabel('time')
plt.ylabel('size')
plt.title('Size of Tree')
plt.show()